--- #YAML:1.0
name:               Business-PostNL
version:            0.13
abstract:           Calculate Dutch (PostNL) shipping costs
author:
    - M. Blom (blom@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Class::Accessor::Fast:  0
    List::Util:           0
    Test::Simple:         0.44
    YAML:                 0
resources:
    repository:  https://github.com/b10m/p5-Business-PostNL
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
